### ISSUE TITLE
Edits to kits: Requested via garth

### ISSUE THREAD

**Issue by xXXIMMATTHEWXXx** [DesertedPvPDev/DesertedPvP#1]
- Finish kits : Pyro Ninja, Edit Golem, Edit Ninja.
Golem
- Debuff to strength 1 with a plain wood sword no sharpness 1
Pyro Ninja
- Gear does not go on correctly.
Ninja
- Edit chestplate to chain instead of iron.

**Comment by Mariozgr8** [comment]
- Ninja and Golem Kits have been fixed

**Comment by Mariozgr8** [comment]
- PyroNinja has been fixed
